import { Button, Group, Modal } from "@mantine/core";
import { storyStore } from "../../stores/storyStore";
import { dataStore } from "../../stores/dataStore";
import { IoInformationCircleOutline } from "react-icons/io5";

function AboutModal() {
  const {
    aboutModalOpened,
    setAboutModalOpened,
    themeView,
    chapterView,
    yAxis,
    isBackendActive,
  } = storyStore();

  const { data } = dataStore();

  const closeModal = () => {
    setAboutModalOpened(false);
  };

  return (
    <Modal
      opened={aboutModalOpened}
      onClose={() => closeModal()}
      title="📔 About Story Ribbons"
      centered
      size={"lg"}
      id="about-modal"
    >
      {!isBackendActive && (
        <p className="disclaimer">
          <b>
            Note: Backend is not active. Please{" "}
            <a
              href="https://github.com/catherinesyeh/story-viz/"
              target="_blank"
              title="Github repo"
            >
              run locally
            </a>{" "}
            to try out LLM-powered features!
          </b>
        </p>
      )}
      <p>
        <b className="grad">Story Ribbons</b> is an interactive literary
        analysis tool that visualizes story interactions over time. You are
        currently exploring the story: <b>{data["title"]}</b>. All insights were
        generated by a large language model.
      </p>
      <p>
        🎗️ Each "ribbon" represents a <b>{themeView ? "theme" : "character"}</b>{" "}
        in the current story (configurable in the <i>Visualization Settings</i>{" "}
        toolbar). You can customize the unit of time along the{" "}
        <span className="emph">x-axis</span> (current:{" "}
        <b>{chapterView ? "chapters" : "scenes"}</b>) and choose what the{" "}
        <span className="emph">y-axis</span> represents (current: <b>{yAxis}</b>
        ). Hovering on a character/theme, location, or scene will bring up an
        overlay with additional information.
      </p>
      <p>
        ✨ Our storyline visualizations are further customizable with the by
        opening the{" "}
        <i>
          {themeView ? "Theme" : "Character"} /{" "}
          {chapterView ? "Chapter" : "Scene"} Settings
        </i>{" "}
        on the right. Here, you can choose what the{" "}
        <span className="emph">color</span> of each ribbon represents, and
        change the <span className="emph">color</span> /{" "}
        <span className="emph">size</span> /{" "}
        <span className="emph">weight</span> encodings of each{" "}
        {chapterView ? "chapter" : "scene"} label.
      </p>
      <p>
        💡 If you need help at any time, click the{" "}
        <IoInformationCircleOutline style={{ marginBottom: -2 }} /> tooltip
        icons around the interface. Thanks for checking out{" "}
        <b className="grad">Story Ribbons!</b>
      </p>
      <Group gap="xs" mt="md">
        <Button size="xs" onClick={() => closeModal()}>
          Start exploring
        </Button>
        <Button
          size="xs"
          onClick={() =>
            window.open("https://catherinesyeh.github.io/story-docs", "_blank")
          }
        >
          Documentation
        </Button>
        <Button
          size="xs"
          onClick={() =>
            window.open("https://arxiv.org/abs/2508.06772", "_blank")
          }
        >
          Paper
        </Button>
        <Button
          size="xs"
          onClick={() =>
            window.open("https://github.com/catherinesyeh/story-viz", "_blank")
          }
        >
          Code
        </Button>
      </Group>
    </Modal>
  );
}

export default AboutModal;
